version: '3'
services:
  api:
    build:
      context: src/api
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1, 5.0
        VARIANT: 5.0
        # Options
        INSTALL_NODE: 'false'
        NODE_VERSION: 'lts/*'
        INSTALL_AZURE_CLI: 'false'
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - .:/workspace:cached
      - ${HOME}/.microsoft/usersecrets:/home/vscode/.microsoft/usersecrets:cached
      - ${HOME}/.aspnet/https:/home/vscode/.aspnet/https:cached
      - ${HOME}/.aws/credentials:/home/vscode/.aws/credentials:cached
      - api-extensions-data:/home/vscode/.vscode-server/extensions
    environment:
      MACHINE_TYPE: computer

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  data:
    build:
      context: src/data
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1, 5.0
        VARIANT: 5.0
        # Options
        INSTALL_NODE: 'false'
        NODE_VERSION: 'lts/*'
        INSTALL_AZURE_CLI: 'false'
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - .:/workspace:cached
      - ${HOME}/.microsoft/usersecrets:/home/vscode/.microsoft/usersecrets:cached
      - ${HOME}/.aws/credentials:/home/vscode/.aws/credentials:cached
      - data-extensions-data:/home/vscode/.vscode-server/extensions
    environment:
      MACHINE_TYPE: computer

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  spa:
    build:
      context: src/spa
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - .:/workspace:cached
      - spa-extensions-data:/home/node/.vscode-server/extensions
    environment:
      MACHINE_TYPE: computer
      NODE_TLS_REJECT_UNAUTHORIZED: 0

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      # - mariadb-data:/var/lib/mysql
      - ./src/sql/migration.sql:/docker-entrypoint-initdb.d/1.sql
      - ./src/sql/states.sql:/docker-entrypoint-initdb.d/2.sql
      - ./src/sql/admins.sql:/docker-entrypoint-initdb.d/3.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  # mariadb-data:
  api-extensions-data:
  data-extensions-data:
  spa-extensions-data:
