# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  lmsprod:
    image: lmsprod
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ${HOME}/.aspnet/https:/https:ro
      - ${HOME}/.aws/credentials:/home/appuser/.aws/credentials:ro
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERT_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${CERT_PATH}
      ASPNETCORE_URLS: https://+:443;http://+:80
      # AwsSettings_Test: Env var
      # ASPNETCORE_ENVIRONMENT: Development

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  mariadb-data:
