import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { StateDto } from 'src/dto/models';

@Injectable({
  providedIn: 'root'
})
export class StateService {
  private statesObject: StateDto[] = [
    { id: 1, abbreviations: 'AL', name: 'Alabama' },
    { id: 2, abbreviations: 'AK', name: 'Alaska' },
    { id: 3, abbreviations: 'AR', name: 'Arkansas' },
    { id: 4, abbreviations: 'AZ', name: 'Arizona' },
    { id: 5, abbreviations: 'CA', name: 'California' },
    { id: 6, abbreviations: 'CO', name: 'Colorado' },
    { id: 7, abbreviations: 'CT', name: 'Connecticut' },
    { id: 8, abbreviations: 'DC', name: 'District of Columbia' },
    { id: 9, abbreviations: 'DE', name: 'Delaware' },
    { id: 10, abbreviations: 'FL', name: 'Florida' },
    { id: 11, abbreviations: 'GA', name: 'Georgia' },
    { id: 12, abbreviations: 'HI', name: 'Hawaii' },
    { id: 13, abbreviations: 'ID', name: 'Idaho' },
    { id: 14, abbreviations: 'IL', name: 'Illinois' },
    { id: 15, abbreviations: 'IN', name: 'Indiana' },
    { id: 16, abbreviations: 'IA', name: 'Iowa' },
    { id: 17, abbreviations: 'KS', name: 'Kansas' },
    { id: 18, abbreviations: 'KY', name: 'Kentucky' },
    { id: 19, abbreviations: 'LA', name: 'Louisiana' },
    { id: 20, abbreviations: 'ME', name: 'Maine' },
    { id: 21, abbreviations: 'MD', name: 'Maryland' },
    { id: 22, abbreviations: 'MA', name: 'Massachusetts' },
    { id: 23, abbreviations: 'MI', name: 'Michigan' },
    { id: 24, abbreviations: 'MN', name: 'Minnesota' },
    { id: 25, abbreviations: 'MS', name: 'Mississippi' },
    { id: 26, abbreviations: 'MO', name: 'Missouri' },
    { id: 27, abbreviations: 'MT', name: 'Montana' },
    { id: 28, abbreviations: 'NE', name: 'Nebraska' },
    { id: 29, abbreviations: 'NH', name: 'New Hampshire' },
    { id: 30, abbreviations: 'NJ', name: 'New Jersey' },
    { id: 31, abbreviations: 'NM', name: 'New Mexico' },
    { id: 32, abbreviations: 'NY', name: 'New York' },
    { id: 33, abbreviations: 'NC', name: 'North Carolina' },
    { id: 34, abbreviations: 'NV', name: 'Nevada' },
    { id: 35, abbreviations: 'ND', name: 'North Dakota' },
    { id: 36, abbreviations: 'OH', name: 'Ohio' },
    { id: 37, abbreviations: 'OK', name: 'Oklahoma' },
    { id: 38, abbreviations: 'OR', name: 'Oregon' },
    { id: 39, abbreviations: 'PA', name: 'Pennsylvania' },
    { id: 40, abbreviations: 'RI', name: 'Rhode Island' },
    { id: 41, abbreviations: 'SC', name: 'South Carolina' },
    { id: 42, abbreviations: 'SD', name: 'South Dakota' },
    { id: 43, abbreviations: 'TN', name: 'Tennessee' },
    { id: 44, abbreviations: 'TX', name: 'Texas' },
    { id: 45, abbreviations: 'UT', name: 'Utah' },
    { id: 46, abbreviations: 'VT', name: 'Vermont' },
    { id: 47, abbreviations: 'VA', name: 'Virginia' },
    { id: 48, abbreviations: 'WA', name: 'Washington' },
    { id: 49, abbreviations: 'WV', name: 'West Virginia' },
    { id: 50, abbreviations: 'WI', name: 'Wisconsin' },
    { id: 51, abbreviations: 'WY', name: 'Wyoming' }
  ];
  private states: string[] = [
    'Alaska',
    'Alabama',
    'Arkansas',
    'American Samoa',
    'Arizona',
    'California',
    'Colorado',
    'Connecticut',
    'District of Columbia',
    'Delaware',
    'Florida',
    'Georgia',
    'Guam',
    'Hawaii',
    'Iowa',
    'Idaho',
    'Illinois',
    'Indiana',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Massachusetts',
    'Maryland',
    'Maine',
    'Michigan',
    'Minnesota',
    'Missouri',
    'Mississippi',
    'Montana',
    'North Carolina',
    'North Dakota',
    'Nebraska',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'Nevada',
    'New York',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Virginia',
    'Virgin Islands',
    'Vermont',
    'Washington',
    'Wisconsin',
    'West Virginia',
    'Wyoming'
  ];

  private tests: string[] = [
    'AK',
    'AL',
    'AR',
    'AZ',
    'CA',
    'CO',
    'CT',
    'DC',
    'DE',
    'FL',
    'GA',
    'HI',
    'IA',
    'ID',
    'IL',
    'IN',
    'KS',
    'KY',
    'LA',
    'MA',
    'MD',
    'ME',
    'MI',
    'MN',
    'MO',
    'MS',
    'MT',
    'NC',
    'ND',
    'NE',
    'NH',
    'NJ',
    'NM',
    'NV',
    'NY',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VA',
    'VT',
    'WA',
    'WI',
    'WV',
    'WY'
  ];

  constructor() {}

  getStates(): string[] {
    return this.states;
  }

  getStatesObject(): Observable<StateDto[]> {
    // return this.statesObject;
    return of(this.statesObject);
  }
}
