insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        1,
        'Larry',
        'Johnson',
        '2018-10-18 07:19:33',
        'b@x.com',
        'B@X.COM',
        'b@x.com',
        'B@X.COM',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '2455387150',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        2,
        'Larry',
        'Johnson',
        '2018-10-18 07:19:33',
        'a@x.com',
        'A@X.COM',
        'a@x.com',
        'A@X.COM',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '2455387150',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        3,
        'Tally',
        'Reuter',
        '2018-10-18 07:19:33',
        'treuter0@businessweek.com',
        'TREUTER0@BUSINESSWEEK.COM',
        'treuter0@businessweek.com',
        'TREUTER0@BUSINESSWEEK.COM',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '2455387150',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        4,
        'Beatrix',
        'Vezey',
        '2018-10-03 14:41:17',
        'bvezey1@sun.com',
        'BVEZEY1@SUN.COM',
        'bvezey1@sun.com',
        'BVEZEY1@SUN.COM',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '8597163372',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        5,
        'Erin',
        'Mansbridge',
        '2018-01-08 16:36:57',
        'emansbridge2@digg.com',
        'EMANSBRIDGE2@DIGG.COM',
        'emansbridge2@digg.com',
        'EMANSBRIDGE2@DIGG.COM',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '1969104757',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        6,
        'Rocky',
        'Males',
        '2018-07-09 13:09:41',
        'rmales3@reuters.com',
        'RMALES3@REUTERS.COM',
        'rmales3@reuters.com',
        'RMALES3@REUTERS.COM',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '2146725154',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        7,
        'Allix',
        'Fidell',
        '2018-12-09 05:30:52',
        'afidell4@constantcontact.com',
        'AFIDELL4@CONSTANTCONTACT.COM',
        'afidell4@constantcontact.com',
        'AFIDELL4@CONSTANTCONTACT.COM',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '5341704997',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        8,
        'Babara',
        'Carlyon',
        '2018-05-15 23:30:18',
        'bcarlyon5@51.la',
        'BCARLYON5@51.LA',
        'bcarlyon5@51.la',
        'BCARLYON5@51.LA',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '4074605391',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        9,
        'Gregoor',
        'Rutigliano',
        '2018-01-08 01:57:51',
        'grutigliano6@yolasite.com',
        'GRUTIGLIANO6@YOLASITE.COM',
        'grutigliano6@yolasite.com',
        'GRUTIGLIANO6@YOLASITE.COM',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '5627380040',
        0,
        0,
        null,
        0,
        0,
        0
    );
insert into AspNetUsers (
        Id,
        FirstName,
        Lastname,
        Created,
        UserName,
        NormalizedUserName,
        Email,
        NormalizedEmail,
        EmailConfirmed,
        PasswordHash,
        SecurityStamp,
        ConcurrencyStamp,
        PhoneNumber,
        PhoneNumberConfirmed,
        TwoFactorEnabled,
        LockoutEnd,
        AccessFailedCount,
        LockoutEnabled,
        IsAccountActivated
    )
values (
        10,
        'Obediah',
        'Gouinlock',
        '2018-08-07 18:32:29',
        'ogouinlock7@wordpress.org',
        'OGOUINLOCK7@WORDPRESS.ORG',
        'ogouinlock7@wordpress.org',
        'OGOUINLOCK7@WORDPRESS.ORG',
        0,
        'AQAAAAEAACcQAAAAEIjZTFkEZdoL3Qo+Ly7pq0BscqMOdo2ObJBP0fpmjWcjfQQ+KUBEnwc1r+qUEaFvlw==',
        'B2MN5CRBTNQ5GOUTOK3M3VPQHHTGC7QS',
        '7eeccff1-7cb1-48cd-87bd-527aa4dd8e21',
        '8224368134',
        0,
        0,
        null,
        0,
        0,
        0
    );
-- Admin User Roles
insert into AspNetUserRoles (UserId, RoleId)
values (1, 2);
insert into AspNetUserRoles (UserId, RoleId)
values (2, 3);
insert into AspNetUserRoles (UserId, RoleId)
values (3, 3);
insert into AspNetUserRoles (UserId, RoleId)
values (4, 2);
insert into AspNetUserRoles (UserId, RoleId)
values (5, 2);
insert into AspNetUserRoles (UserId, RoleId)
values (6, 2);
insert into AspNetUserRoles (UserId, RoleId)
values (7, 2);
insert into AspNetUserRoles (UserId, RoleId)
values (8, 3);
insert into AspNetUserRoles (UserId, RoleId)
values (9, 3);
insert into AspNetUserRoles (UserId, RoleId)
values (10, 3);
